# Generated by Django 3.0.6 on 2020-05-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='new_search',
            new_name='search',
        ),
    ]
